apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: '9.9.1'
    helm:
      releaseName: gitlab-prod
      values: |
        global:
          hosts:
            domain: "gitlab.ailabtools.org"
            https: true
            externalIP: "172.29.61.100"
            gitlab:
              name: "gitlab.ailabtools.org"
            minio:
              name: "gitlab-minio.ailabtools.org"
            # registry:
            #   name: "gitlab-registry.ailabtools.org"
          ingress:
            class: "nginx"
          kas:
            enabled: false
          minio:
            enable: false
          appConfig:
            artifacts:
              bucket: "ailab-gitlab-artifacts"
            lfs:
              bucket: "ailab-gitlab-lfs"
            uploads:
              bucket: "ailab-gitlab-uploads"
            packages:
              bucket: "ailab-gitlab-packages"
            backups:
              bucket: "ailab-gitlab-backups"
              tmpBucket: "ailab-gitlab-tmp"
            pages:
              enabled: true
              objectStore:
                enabled: true
                bucket: "ailab-gitlab-pages"
            registry:
              bucket: "ailab-gitlab-registry"
            terraformState:
              bucket: "ailab-gitlab-terraform-state"
            externalDiffs:
              bucket: "ailab-gitlab-external-diffs"
            dependencyProxy:
              bucket: "ailab-gitlab-dependency-proxy"
            ciSecureFiles:
              bucket: "ailab-gitlab-ci-secure-files"
            object_store:
              enabled: true
              proxy_download: false
              connection:
                secret: gitlab-s3-creds 
        
        upgradeCheck:
            enabled: false

        certmanager-issuer:
          email: "polenovsasa1@gmail.com"

        nginx-ingress:
          enabled: false

        gitlab:
          toolbox:
            persistence:
              enabled: true
              size: 500Gi
              storageClass: "csi-disk-dss"
          webservice:
            nginx:
              clientMaxBodySize: "512m"
          # migrations:
          #   enabled: false
          gitlab-exporter:
            enabled: false

        gitlab-runner:
          install: false

        prometheus:
          install: false

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true