apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-preprod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: '9.9.0'
    helm:
      releaseName: gitlab-preprod
      values: |
        global:
          hosts:
            domain: "ailab-gitlab-preprod.ailabtools.org"
            https: true
            gitlab:
              name: "ailab-gitlab-preprod.ailabtools.org"
          ingress:
            configureCertmanager: false
            class: "nginx"
            tls:
              enabled: true
              secretName: gitlab-ssl
          railsSecrets:
            secret: gitlab-backup
            key: secrets.yml
          kas:
            enabled: false
          minio:
            enabled: false
          appConfig:
            artifacts:
              bucket: "ailab-gitlab-artifacts"
              connection:
                secret: gitlab-s3
                key: connection
            lfs:
              bucket: "ailab-gitlab-lfs"
              connection:
                secret: gitlab-s3
                key: connection
            uploads:
              bucket: "ailab-gitlab-uploads"
              connection:
                secret: gitlab-s3
                key: connection
            packages:
              bucket: "ailab-gitlab-packages"
              connection:
                secret: gitlab-s3
                key: connection
            backups:
              bucket: "ailab-gitlab-backups"
              tmpBucket: "ailab-gitlab-tmp"
              connection:
                secret: gitlab-s3
                key: connection
            # pages:
            #   enabled: true
            #   objectStore:
            #     enabled: true
            #     bucket: "ailab-gitlab-pages"
            registry:
              enabled: true
              storage:
                s3:
                  secret: gitlab-registry-s3
            # terraformState:
            #   bucket: "ailab-gitlab-terraform-state"
            # externalDiffs:
            #   bucket: "ailab-gitlab-external-diffs"
            # dependencyProxy:
            #   bucket: "ailab-gitlab-dependency-proxy"
            # ciSecureFiles:
            #   bucket: "ailab-gitlab-ci-secure-files"
            # object_store:
            #   enabled: true
            #   proxy_download: false
          
        upgradeCheck:
            enabled: false

        nginx-ingress:
          enabled: false

        gitlab:
          toolbox:
            persistence:
              enabled: true
              size: 500Gi
              storageClass: "csi-disk-dss"
            backups:
              objectStorage:
                config:
                  secret: gitlab-s3cfg-backup
          gitaly:
            persistence:
              enabled: true
              size: 250Gi
              storageClass: "csi-disk-dss"
          webservice:
            nginx:
              clientMaxBodySize: "512m"
          # migrations:
          #   enabled: false
          gitlab-exporter:
            enabled: false

        gitlab-runner:
          install: false

        prometheus:
          install: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true