apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-preprod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: '9.9.1'
    helm:
      releaseName: gitlab-preprod
      values: |
        global:
          hosts:
            domain: "ailab-gitlab-preprod.ailabtools.org"
            https: true
            gitlab:
              name: "ailab-gitlab-preprod.ailabtools.org"
          ingress:
            configureCertmanager: false
            class: "nginx"
            tls:
              enabled: true
              secretName: wildcard-ailabtools-tls
          kas:
            enabled: false
        
        upgradeCheck:
            enabled: false

        nginx-ingress:
          enabled: false

        gitlab:
          toolbox:
            persistence:
              enabled: true
              size: 500Gi
              storageClass: "csi-disk-dss"
          webservice:
            nginx:
              clientMaxBodySize: "512m"
          migrations:
            enabled: false
          gitlab-exporter:
            enabled: false

        gitlab-runner:
          install: false

        prometheus:
          install: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true