apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-preprod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: '9.9.0'
    helm:
      releaseName: gitlab-preprod
      values: |
        global:
          hosts:
            domain: "ailab-gitlab-preprod.ailabtools.org"
            https: true
            gitlab:
              name: "ailab-gitlab-preprod.ailabtools.org"
          ingress:
            class: "nginx"
            configureCertmanager: false
            tls:
              enabled: true
              secretName: gitlab-tls
          railsSecrets:
            secret: gitlab-backup  
          kas:
            enabled: false  
          minio:
            enabled: false
          appConfig:
            artifacts:
              bucket: ailab-gitlab-artifacts
            lfs:
              bucket: ailab-gitlab-lfs
            uploads:
              bucket: ailab-gitlab-uploads
            packages:
              bucket: ailab-gitlab-packages
            backups:
              bucket: ailab-gitlab-backups
              tmpBucket: ailab-gitlab-tmp
            registry:
              bucket: ailab-gitlab-registry
            object_store:
              connection:
                secret: gitlab-object-storage
              enabled: true
              proxy_download: false
          
        upgradeCheck:
            enabled: false

        nginx-ingress:
          enabled: false

        gitlab:
          toolbox:
            persistence:
              enabled: true
              size: 500Gi
              storageClass: "csi-disk-dss"
            backups:
              objectStorage:
                config:
                  secret: gitlab-s3cfg-backup
          gitaly:
            persistence:
              enabled: true
              size: 256Gi
              storageClass: "csi-disk-dss"
          webservice:
            nginx:
              clientMaxBodySize: "512m"
          gitlab-exporter:
            enabled: false

        registry:
          storage:
            secret: gitlab-registry-storage
            key: config

        gitlab-runner:
          install: false

        prometheus:
          install: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true